version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: eventify-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: eventify
    volumes:
      - mongodb_data:/data/db

  backend:
    build: ./bakend
    container_name: eventify-backend
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/eventify
      - JWT_SECRET=your_production_jwt_secret_here
      - PORT=4000
    depends_on:
      - mongodb
    volumes:
      - ./bakend:/app
      - /app/node_modules

  frontend:
    build: ./Frontend
    container_name: eventify-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:4000/api
    depends_on:
      - backend

volumes:
  mongodb_data:
